version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: yourdatabase
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - C:\Attach\docker\volumes\Postgres\Scripts:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_URL: jdbc:postgresql://db:5432/yourdatabase
      DB_USER: username
      DB_PASSWORD: password
